### ISSUE TITLE
License

### ISSUE THREAD

**Issue by QuentinCG** [lingonsaft/clicker-app#34]
Hello,

I would like to use your [notification widget](https://github.com/lingonsaft/clicker-app/blob/master/lib/lib/showNotification.dart) for some of my flutter/android projects.
What kind of license has this project?

I would suggest [MIT ](https://en.wikipedia.org/wiki/MIT_License) or [any other open source license](https://opensource.org/licenses) that allows us to use it in any context (with credits).

Thanks in advance for your response
Quentin

**Comment by richie-south** [comment]
I'm author you can use it however you want :) This dossen't need any license 😃

**Comment by QuentinCG** [comment]
Thanks a lot !
